---
apiVersion: v2
description: A chart to power Immich running on kubernetes
name: immich
version: 1.0.2
maintainers:
  - name: julian
    email: julian@diluz.io
dependencies:
  - name: immich
    repository: oci://ghcr.io/maybeanerd/immich-charts
    version: 0.10.21
