network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      addresses:
        - "{{specific_node_ip}}/24"
      dhcp4: no
      routes:
        - to: 0.0.0.0/0 #Standardroute für IPv4
          via: 192.168.178.1
      nameservers:
        addresses: [192.168.178.49, 1.1.1.1, 8.8.8.8] # I'm actually not sure why I put the 49 here ._.
