---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.0.1/charts/other/app-template/values.schema.json
controllers:
  main:
    containers:
      main:
        image:
          repository: linuxserver/obsidian
          tag: 1.9.12
          pullPolicy: IfNotPresent
        probes:
          liveness:
            enabled: true
            custom: true
            port: http
            path: /
            type: TCP
        # resources:
        #   requests:
        #     cpu: 10m
        #     memory: 256M
        #   limits:
        #     memory: 512M
service:
  main:
    controller: main
    type: ClusterIP
    # externalTrafficPolicy: Local
    ports:
      http:
        enabled: true
        port: 80
        protocol: TCP
        targetPort: 3000
      https:
        enabled: true
        port: 443
        protocol: TCP
        targetPort: 3001
      websocket:
        enabled: true
        port: 8082
        protocol: TCP
        targetPort: 8082
ingress:
  main:
    enabled: true
    tls:
      - hosts:
          - obsidian.cluster
    hosts:
      - host: obsidian.cluster
        paths:
          - path: /
            service:
              identifier: main
              port: http
          - path: /
            service:
              identifier: main
              port: https
          - path: /
            service:
              identifier: main
              port: http
persistence:
  config:
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 50Gi
    globalMounts:
      - path: /notes
