apiVersion: v2
description: A Vaultwarden Helm chart for Kubernetes
name: vaultwarden
version: 0.1.4
maintainers:
  - name: julian
    email: julian@diluz.io
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 4.6.0
