---
apiVersion: v2
description: A chart to run traefik ingress
name: traefik
version: 0.1.2
maintainers:
  - name: julian
    email: julian@diluz.io
dependencies:
  - name: traefik
    repository: https://traefik.github.io/charts
    version: 41.0.2
