---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/app-template-4.0.1/charts/other/app-template/values.schema.json
controllers:
  main:
    pod:
      dnsConfig:
        options:
          - { name: ndots, value: "1" }
      securityContext:
        runAsNonRoot: false # Adguard doesn't support running as non-root
        runAsUser: 0
        # runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
    containers:
      main:
        image:
          repository: adguard/adguardhome
          tag: v0.107.54@sha256:ec59d9d8d083b74620f827879bee7ad88621f96bc0c4347c84c176ffa349484c
          pullPolicy: IfNotPresent
        env:
          TZ: UTC
        probes:
          liveness:
            enabled: true
            custom: true
            port: 80
            path: /
            type: TCP
        resources:
          requests:
            cpu: 10m
            memory: 256M
          limits:
            memory: 512M
service:
  main:
    controller: main
    type: LoadBalancer
    externalTrafficPolicy: Local
    annotations:
      external-dns.alpha.kubernetes.io/hostname: "dns.local"
    ports:
      http:
        enabled: true
        port: 80
        protocol: TCP
        targetPort: 80
      dns-tcp:
        enabled: true
        port: 53
        protocol: TCP
        targetPort: 53
      dns-udp:
        enabled: true
        port: 53
        protocol: UDP
        targetPort: 53
      dns-tcp-tls:
        enabled: true
        port: 853
        protocol: TCP
        targetPort: 853
ingress:
  main:
    enabled: true
    annotations:
      gethomepage.dev/enabled: "true"
      gethomepage.dev/description: "DNS Ad-Blocking"
      gethomepage.dev/group: Network
      gethomepage.dev/icon: adguard-home.svg
      gethomepage.dev/name: AdGuard
      gethomepage.dev/widget.url: http://adguard.network.svc.cluster.local:80
    hosts:
      - host: adguard.local
        paths:
          - path: /
            service:
              identifier: main
              port: http
persistence:
  config-work:
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /opt/adguardhome/work
  config-conf:
    storageClass: nfs-client
    accessMode: ReadWriteOnce
    size: 1Gi
    globalMounts:
      - path: /opt/adguardhome/conf
